# Generated by Django 5.1.1 on 2024-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realestate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                ("image", models.ImageField(upload_to="realestate_photos/")),
                ("imageLg", models.ImageField(upload_to="estate_photos/")),
                ("country", models.TextField()),
                ("address", models.TextField()),
                ("bedrooms", models.TextField()),
                ("bathrooms", models.TextField()),
                ("surface", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=200)),
            ],
        ),
    ]
