# Generated by Django 5.1.1 on 2024-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0002_remove_realestate_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="bathrooms",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="bedrooms",
            field=models.IntegerField(),
        ),
    ]
