# Generated by Django 5.1.1 on 2024-09-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("byers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Byer",
        ),
    ]
