# Generated by Django 5.1.1 on 2024-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("byers", "0002_delete_byer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Byer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("house", models.CharField(max_length=50)),
            ],
        ),
    ]
